name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Create matrix ⊹
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 4

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  run-test:
    needs: prepare
    if: always()
    name: 'Run tests'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          message: 'Starting Cypress tests...${{ strategy.job-index }}'
          matrix: ${{ toJson(matrix) }}
        if: always()
      - name: Git clone
        uses: actions/checkout@v4

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Check for duplicated file names
        run: |
          git ls-files --exclude-standard --others --cached --no-empty-directory | sort -f > files.txt
          uniq -di files.txt > duplicates.txt
          if [[ -s duplicates.txt ]]; then
            echo "Found files with the same name:"
            cat duplicates.txt
            exit 1
          fi

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      # Install npm dependencies, cache them correctly
      - name: Install dependencies and cache them
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Catch "it.only" 🫴
        id: check-only
        run: npm run stop-only

      - name: Static analysis
        id: static-analysis
        run: npm run format && npm run lint

      - name: Prepare Jenkins data
        run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_home.tar.0* > ${{ github.workspace }}/jenkins_backup.tar
          md5sum ${{ github.workspace }}/jenkins_backup.tar

      - name: Extract Jenkins data and set permission
        run: |
          tar -xvf ./jenkins_backup.tar
          chmod -R 777 ./jenkins_home

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach -p 8081:8080 -p 50000:50000 -v ${{ github.workspace }}/jenkins_home:/var/jenkins_home jenkins/jenkins:2.462.3-lts-jdk17

      - name: Wait for the Jenkins
        run: chmod +x ./.github/wait-for-jenkins.sh

      - name: Write the cypress.env.json
        run: |
          echo '${{ secrets.CYPRESS_LOGIN_CREDENTIALS }}' > ./cypress.env.json

      - name: Run Cypress tests 🧪
        id: cypress-tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Upload Allure Results
        id: upload-allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{strategy.job-index }}
          path: report/allure-results
          if-no-files-found: ignore
          retention-days: 1

      - name: Upload Accessibility Reports
        id: upload-accessibility-reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{strategy.job-index }}
          path: reports
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload screenshots Results
        id: upload-screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{strategy.job-index }}
          path: cypress/screenshots
          if-no-files-found: ignore
          retention-days: 1
      # - uses: act10ns/slack@v2
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     message: "Report URL for job ${{ job.status }}: ${{ job.name }} - https://valiantsin2021.github.io/Cypress-Jenkins"
      #   if: always()
  generate-report:
    runs-on: ubuntu-latest
    needs: run-test
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Download all Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results-*

      - name: Merge Allure Results
        if: success()
        run: |
          # Combine all downloaded result folders into a single allure-results directory
          mkdir -p final-allure-results
          cp -r allure-results/allure-results-*/* final-allure-results/

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        with:
          gh_pages: gh-pages
          allure_results: final-allure-results
          allure_history: allure-history
          allure_report: allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure report
          path: allure-report
          if-no-files-found: ignore

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Notify Slack
        if: always()
        run: |
          npm ci
          find . -type f -name "summary.json" | xargs -I {} node ./cypress/support/reporter.js {}
