name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Create matrix ⊹
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  run-test:
    needs: prepare
    if: always()
    name: 'Run tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Check for duplicated file names
        run: |
          git ls-files --exclude-standard --others --cached --no-empty-directory | sort -f > files.txt
          uniq -di files.txt > duplicates.txt
          if [[ -s duplicates.txt ]]; then
            echo "Found files with the same name:"
            cat duplicates.txt
            exit 1
          fi

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      # Install npm dependencies, cache them correctly
      - name: Install dependencies and cache them
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Catch "it.only" 🫴
        run: npm run stop-only

      - name: Static analysis
        run: npm run format && npm run lint

      - name: Prepare Jenkins data
        run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_home.tar.0* > ${{ github.workspace }}/jenkins_backup.tar
          md5sum ${{ github.workspace }}/jenkins_backup.tar

      - name: Extract Jenkins data and set permission
        run: |
          tar -xvf ./jenkins_backup.tar
          chmod -R 777 ./jenkins_home

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach -p 8081:8080 -p 50000:50000 -v ${{ github.workspace }}/jenkins_home:/var/jenkins_home jenkins/jenkins:2.462.3-lts-jdk17

      - name: Wait for the Jenkins
        run: chmod +x ./.github/wait-for-jenkins.sh

      - name: Write the cypress.env.json
        run: |
          echo '${{ secrets.CYPRESS_LOGIN_CREDENTIALS }}' > ./cypress.env.json

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          install: false
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{strategy.job-index }}
          path: allure-results
          retention-days: 1

      - name: Upload screenshots Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{strategy.job-index }}
          path: cypress/screenshots
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: run-test
    if: always()
    steps:
      - name: Download all Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results-*

      - name: Merge Allure Results
        if: success()
        run: |
          # Combine all downloaded result folders into a single allure-results directory
          mkdir -p final-allure-results
          cp -r allure-results-*/* final-allure-results/

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        with:
          allure_results: final-allure-results
          allure_report: allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure report
          path: allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
